### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by tmtkzk0823** [ippei-shimizu/buzzbase#36]
@ippei-shimizu 
疲れ様です！
MVPリリースお疲れ様でした！
全体的にかなり良くできていて、ユーザビリティも高く、既に就活で通用するアプリケーションだと思いました！

1点だけ、気になったところがあるのでFBとしてお伝えせていただきますね！

- `app/models/pitching_result.rb`などに記載されている計算ロジック（`self.pitching_stats_for_user`メソッド等）に数字がそのまま使用されているので、可能な範囲で定数に置き換えてもいいかなと思いました！（マジックナンバー）

以上です！

非常にレベルの高いアプリだと思います！
LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by ippei-shimizu** [comment]
@tmtkzk0823 
MVPレビューありがとうございました！

そして、マジックナンバーのご指摘ありがとうございます！確かに、野球に関する数値になるので、定数に置き換えた方が良いと思いますので、タスクに組み込みたいと思います！

また、スケジュールが決まりましたら、ご共有させていただきます！
